DROP TABLE IF EXISTS grr_etablissement;
CREATE TABLE grr_etablissement ( id int(11) NOT NULL auto_increment,code varchar(20) default NULL UNIQUE,shortname varchar(30) NOT NULL default '',name varchar(50) NOT NULL default '',codepostal varchar(50) default NULL,adresse varchar(50) default NULL,ville varchar(50) default NULL,PRIMARY KEY (`id`));
DROP TABLE IF EXISTS grr_setting_etablissement;
CREATE TABLE grr_setting_etablissement (  NAME varchar(32) NOT NULL default '',  VALUE text NOT NULL, code_etab varchar(20) NOT NULL,  PRIMARY KEY  (NAME, code_etab));
DROP TABLE IF EXISTS grr_j_etablissement_site;
CREATE TABLE grr_j_etablissement_site (id_etablissement int(11) NOT NULL default '0', id_site int(11) NOT NULL default '0', PRIMARY KEY  (id_etablissement,id_site) );
DROP TABLE IF EXISTS grr_j_user_etablissement;
CREATE TABLE grr_j_user_etablissement (login varchar(40) NOT NULL default '', id_etablissement int(11) NOT NULL default '0', PRIMARY KEY  (login,id_etablissement) );
DROP TABLE IF EXISTS grr_j_useradmin_etablissement;
CREATE TABLE grr_j_useradmin_etablissement (login varchar(40) NOT NULL default '', id_etablissement int(11) NOT NULL default '0', PRIMARY KEY  (login,id_etablissement) );
DROP TABLE IF EXISTS grr_j_etablissement_type_area;
CREATE TABLE grr_j_etablissement_type_area (id_type_area int(11) NOT NULL default '0', id_etablissement int(11) NOT NULL default '0', PRIMARY KEY  (id_type_area,id_etablissement) );
DROP TABLE IF EXISTS grr_j_etablissement_calendar;
CREATE TABLE grr_j_etablissement_calendar (DAY int(11) NOT NULL default '0', id_etablissement int(11) NOT NULL default '0');
DROP TABLE IF EXISTS grr_session;
CREATE TABLE grr_session (sess_id char(40) NOT NULL, sess_datas text , sess_expire 	bigint(20) );
DROP TABLE IF EXISTS grr_etablissement_regroupement;
CREATE TABLE grr_etablissement_regroupement (code_etablissement_secondaire varchar(20) NOT NULL, code_etablissement_principal varchar(20) NOT NULL);

DROP TABLE IF EXISTS grr_j_mailuser_room;
CREATE TABLE grr_j_mailuser_room (login varchar(40) NOT NULL default '', id_room int(11) NOT NULL default '0', PRIMARY KEY  (login,id_room) );
DROP TABLE IF EXISTS grr_j_user_area;
CREATE TABLE grr_j_user_area (login varchar(40) NOT NULL default '', id_area int(11) NOT NULL default '0', PRIMARY KEY  (login,id_area) );
DROP TABLE IF EXISTS grr_j_user_room;
CREATE TABLE grr_j_user_room (login varchar(40) NOT NULL default '', id_room int(11) NOT NULL default '0', PRIMARY KEY  (login,id_room) );
DROP TABLE IF EXISTS grr_j_useradmin_area;
CREATE TABLE grr_j_useradmin_area (login varchar(40) NOT NULL default '', id_area int(11) NOT NULL default '0', PRIMARY KEY  (login,id_area) );
DROP TABLE IF EXISTS grr_log;
CREATE TABLE grr_log (LOGIN varchar(40) NOT NULL default '', START datetime NOT NULL default '2016-01-01 00:00:00', SESSION_ID varchar(64) NOT NULL default '', REMOTE_ADDR varchar(16) NOT NULL default '', USER_AGENT varchar(255) NOT NULL default '', REFERER varchar(255) NOT NULL default '', AUTOCLOSE enum('0','1')  default '0', END datetime NOT NULL default '2016-01-01 00:00:00', PRIMARY KEY  (SESSION_ID,`START`));
DROP TABLE IF EXISTS grr_area;
CREATE TABLE grr_area (id int(11) NOT NULL auto_increment, area_name varchar(30) NOT NULL default '', access char(1) NOT NULL default '', order_display smallint(6) NOT NULL default '0', ip_adr varchar(15) NOT NULL default '',   morningstarts_area smallint(6) NOT NULL default '0', eveningends_area smallint(6) NOT NULL default '0', duree_max_resa_area INT NOT NULL default '-1', resolution_area INT NOT NULL default '0', eveningends_minutes_area smallint(6) NOT NULL default '0', weekstarts_area smallint(6) NOT NULL default '0', twentyfourhour_format_area smallint(6) NOT NULL default '0', calendar_default_values char(1) NOT NULL default 'y', enable_periods char(1) NOT NULL default 'n', display_days varchar(7) NOT NULL default 'yyyyyyy', id_type_par_defaut int(11) NOT NULL default '-1', duree_par_defaut_reservation_area INT NOT NULL DEFAULT '0', max_booking smallint(6) NOT NULL default '-1', PRIMARY KEY  (id));
DROP TABLE IF EXISTS grr_entry;
CREATE TABLE grr_entry (id int(11) NOT NULL auto_increment, start_time int(11) NOT NULL default '0', end_time int(11) NOT NULL default '0', entry_type int(11) NOT NULL default '0', repeat_id int(11) NOT NULL default '0', room_id int(11) NOT NULL default '1',timestamp timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, create_by varchar(100) NOT NULL default '', beneficiaire_ext varchar(200) NOT NULL default '', beneficiaire varchar(100) NOT NULL default '', name varchar(80) NOT NULL default '', type char(2) NOT NULL default 'A', description text, statut_entry char(1) NOT NULL default '-', option_reservation int(11) NOT NULL default '0',overload_desc text, moderate tinyint(1) default '0', jours int(2) NOT NULL default '0', clef int(2) NOT NULL default '0', courrier int(2) NOT NULL default '0', PRIMARY KEY  (id));
DROP TABLE IF EXISTS grr_repeat;
CREATE TABLE grr_repeat ( id int(11) NOT NULL auto_increment, start_time int(11) NOT NULL default '0', end_time int(11) NOT NULL default '0', rep_type int(11) NOT NULL default '0', end_date int(11) NOT NULL default '0', rep_opt varchar(32) NOT NULL default '', room_id int(11) NOT NULL default '1', timestamp timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, create_by varchar(100) NOT NULL default '', beneficiaire_ext varchar(200) NOT NULL default '', beneficiaire varchar(100) NOT NULL default '', name varchar(80) NOT NULL default '', type char(2) NOT NULL default 'A', description text, rep_num_weeks tinyint(4) default '0',overload_desc text, jours tinyint(2) NOT NULL default '0', courrier int(2) NOT NULL default '0', PRIMARY KEY  (id));
DROP TABLE IF EXISTS grr_room;
CREATE TABLE grr_room ( id int(11) NOT NULL auto_increment,  area_id int(11) NOT NULL default '0',  room_name varchar(60) NOT NULL default '',  description varchar(60) NOT NULL default '',  capacity int(11) NOT NULL default '0',  max_booking smallint(6) NOT NULL default '-1', statut_room char(1) NOT NULL default '1', show_fic_room char(1) NOT NULL default 'n', picture_room varchar(50) NOT NULL default '', comment_room text NOT NULL, show_comment CHAR(1) NOT NULL DEFAULT 'n', delais_max_resa_room smallint(6) NOT NULL default '-1', delais_min_resa_room smallint(6) NOT NULL default '0', allow_action_in_past char(1) NOT NULL default 'n', dont_allow_modify char(1) NOT NULL default 'n', order_display smallint(6) NOT NULL default '0', delais_option_reservation smallint(6) NOT NULL default '0', type_affichage_reser smallint(6) DEFAULT '0' NOT NULL, moderate tinyint(1) default '0', qui_peut_reserver_pour char(1) NOT NULL default '5', active_ressource_empruntee char(1) NOT NULL default 'y', who_can_see SMALLINT DEFAULT '0' NOT NULL, room_warning varchar(255) NOT NULL DEFAULT '', PRIMARY KEY  (id));
DROP TABLE IF EXISTS grr_utilisateurs;
CREATE TABLE grr_utilisateurs (login varchar(40) NOT NULL default '', nom varchar(30) NOT NULL default '', prenom varchar(30) NOT NULL default '', password varchar(32) NOT NULL default '', email varchar(100) NOT NULL default '', statut varchar(30) NOT NULL default '', etat varchar(20) NOT NULL default '', default_site smallint(6) NOT NULL default '0', default_area smallint(6) NOT NULL default '0', default_etablissement smallint(11) NOT NULL default '0', default_room smallint(6) NOT NULL default '0', default_style varchar(50) NOT NULL default '', default_list_type varchar(50) NOT NULL default '', default_language char(3) NOT NULL default '', source varchar(10) NOT NULL default 'local', PRIMARY KEY  (login) );
DROP TABLE IF EXISTS grr_setting;
CREATE TABLE grr_setting (  NAME varchar(32) NOT NULL default '',  VALUE text NOT NULL,  PRIMARY KEY  (NAME));
DROP TABLE IF EXISTS grr_area_periodes;
CREATE TABLE grr_area_periodes (id_area int(11) NOT NULL default '0', num_periode smallint(6) NOT NULL default '0', nom_periode varchar(100) NOT NULL default '', PRIMARY KEY  (`id_area`,`num_periode`));
DROP TABLE IF EXISTS grr_type_area;
CREATE TABLE grr_type_area (id int(11) NOT NULL auto_increment, type_name varchar(30) NOT NULL default '',order_display smallint(6) NOT NULL default '0',couleur smallint(6) NOT NULL default '0',type_letter char(2) NOT NULL default '',disponible VARCHAR(1) NOT NULL DEFAULT '2', PRIMARY KEY  (id));
DROP TABLE IF EXISTS grr_j_type_area;
CREATE TABLE grr_j_type_area (id_type int(11) NOT NULL default '0', id_area int(11) NOT NULL default '0');
DROP TABLE IF EXISTS grr_calendar;
CREATE TABLE grr_calendar (DAY int(11) NOT NULL default '0');
DROP TABLE IF EXISTS grr_calendrier_jours_cycle;
CREATE TABLE grr_calendrier_jours_cycle (DAY int(11) NOT NULL default '0', Jours varchar(20) NOT NULL default '');
DROP TABLE IF EXISTS grr_overload;
CREATE TABLE grr_overload (id int(11) NOT NULL auto_increment, id_area INT NOT NULL, fieldname VARCHAR(25) NOT NULL default '', fieldtype VARCHAR(25) NOT NULL default '', fieldlist text NOT NULL, obligatoire CHAR( 1 ) DEFAULT 'n' NOT NULL, affichage CHAR( 1 ) DEFAULT 'n' NOT NULL, confidentiel CHAR( 1 ) DEFAULT 'n' NOT NULL, overload_mail CHAR( 1 ) DEFAULT 'n' NOT NULL, PRIMARY KEY  (id));
DROP TABLE IF EXISTS grr_entry_moderate;
CREATE TABLE grr_entry_moderate (id int(11) NOT NULL auto_increment, login_moderateur varchar(40) NOT NULL default '',motivation_moderation text NOT NULL,start_time int(11) NOT NULL default '0',end_time int(11) NOT NULL default '0',entry_type int(11) NOT NULL default '0', repeat_id int(11) NOT NULL default '0',room_id int(11) NOT NULL default '1',timestamp timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, create_by varchar(100) NOT NULL default '', beneficiaire_ext varchar(200) NOT NULL default '', beneficiaire varchar(100) NOT NULL default '', name varchar(80) NOT NULL default '',type char(2) default NULL,description text,statut_entry char(1) NOT NULL default '-',option_reservation int(11) NOT NULL default '0',overload_desc text,moderate tinyint(1) default '0', PRIMARY KEY  (id));
DROP TABLE IF EXISTS grr_site;
CREATE TABLE grr_site (id int(11) NOT NULL auto_increment, sitecode varchar(50) default NULL, sitename varchar(50) NOT NULL default '', adresse_ligne1 varchar(38) default NULL, adresse_ligne2 varchar(38) default NULL, adresse_ligne3 varchar(38) default NULL, cp varchar(5) default NULL, ville varchar(50) default NULL, pays varchar(50) default NULL, tel varchar(25) default NULL, fax varchar(25) default NULL, PRIMARY KEY (`id`));
DROP TABLE IF EXISTS grr_j_site_area;
CREATE TABLE grr_j_site_area ( id_site int(11) NOT NULL default '0', id_area int(11) NOT NULL default '0', PRIMARY KEY  (`id_site`,`id_area`));
DROP TABLE IF EXISTS grr_j_useradmin_site;
CREATE TABLE grr_j_useradmin_site (login varchar(40) NOT NULL default '', id_site int(11) NOT NULL default '0', PRIMARY KEY  (login,id_site) );
DROP TABLE IF EXISTS grr_correspondance_statut;
CREATE TABLE grr_correspondance_statut (id int(11) NOT NULL auto_increment, code_fonction varchar(30) NOT NULL, libelle_fonction varchar(200) NOT NULL, statut_grr varchar(30) NOT NULL,  PRIMARY KEY (id));

